### ISSUE TITLE
Double entries in accounting

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#21]
Double sequences, account tags due to the fact that we have 2 chart of accounts.

**Comment by astirpe** [comment]
Added multicompany rule for `ir.sequence` in https://github.com/onesteinbv/addons-container/commit/c2a5f738750eb285eadef9b84e72894960700782

**Comment by astirpe** [comment]
@andreschenkels I'm noticing that the account tags are actually the same as the account groups. So it seems to me that the account tags are not bringing any additional information if compared to account groups. Would it make sense to remove the account tags for all the RGS accounts and leave only the tags for the taxes? Or is there any reason to keep them?

**Comment by astirpe** [comment]
@ThijsvOers you are right, when selecting "Nederlands Referentie Grootboekschema" for the main company, the duplicated sequences are created. This happens every time the user switches the COA schema actually. The problem is caused by OCA module `account_move_name_sequence` and it's clear to me that it's a bug. So I will try to find a solution and propose it to OCA. I'll let you know.

**Comment by astirpe** [comment]
Duplicated sequences fixed in https://github.com/onesteinbv/addons-oca/commit/f3a5efa49a0b1919deb6136412ec0b440eed727e and the fix is also proposed to OCA: https://github.com/OCA/account-financial-tools/pull/1718

**Comment by astirpe** [comment]
@ThijsvOers what do you think regarding account tags? Can be removed?

**Comment by ThijsvOers** [comment]
@astirpe I am not sure, let's leave it like it is for now (enduser will not notice the account tags)
