### ISSUE TITLE
parent_id on account groups

### ISSUE THREAD

**Issue by andreschenkels** [onesteinbv/addons-container#4]
@astirpe I would like the option to define a parent group on account.group without defining from to numbers.

Mainly to create a nice structure not always directly linked to numbers

**Comment by astirpe** [comment]
@andreschenkels 

**_Proposal_**
In case current company has RGS chart of account installed, we could hide `code_prefix_start` and `code_prefix_end` from group view and at the same time add `parent_id` in view (parent_id should be converted to non-readonly).
Since `code_prefix_start` and `code_prefix_end` would be empty,  `_adapt_accounts_for_account_groups()` and `_adapt_parent_account_group() ` would be not executed. Also the `check_length_prefix` constraint would be not triggered.

I didn't try it but I think that it should be working. So it seems do-able to me, or am I missing something?

**Comment by andreschenkels** [comment]
@astirpe I tried to make a fix for this issue. It registers the parent_id without a problem. And I added a module l10n_nl_rgs_account_financial_report to fix the compute_account_ids and naming for the trail balance.

There I have a problem can you have a look? When I change for instance the code of the group it calculates the compute_account_ids correctly but not on install it keeps it empty. The idea is that compute_account_ids gets all the accounts of all the childs and subchilds to get a correct value in the trail balance.

**Comment by astirpe** [comment]
@andreschenkels I will look at it, thanks!

**Comment by astirpe** [comment]
@andreschenkels

I added init hook in https://github.com/onesteinbv/addons-container/commit/8d00beb5b8b05a00abe865407296b74dffafd4c4

Would you check?

**Comment by astirpe** [comment]
Closing as completed
