### ISSUE TITLE
previewer OCA only on account entries and not on formview

### ISSUE THREAD

**Issue by ThijsvOers** [onesteinbv/addons-container#88]
We have implemented the OCA module account_move_line_attachment_preview, we only want to see the pdf preview on account movelines. At the moment this functionality is also visible on the formview of vendor bills/customer invoices. In the formview we want to see the standard odoo community solution.

**Comment by astirpe** [comment]
Temporary patch applied here: https://github.com/onesteinbv/addons-oca/commit/360ac3669eda58b5971e1ff225ff233b358a47ab
The patch disables the OCA preview on the form only and leave it as standard Odoo preview. So it should be OK for the time being.

NOTE:
Since the patch is made an OCA module, it should be modified to make it OCA proof and proposed to OCA. So my suggestion is: disabling the OCA preview on the form should be an optional feature, so that it can be configurable somehow.

I let you decide what to do with this issue: close it after tests or keep it open as a reminder for the future OCA implementation.

**Comment by astirpe** [comment]
See also comment https://github.com/OCA/knowledge/pull/434/files#r1403171727

**Comment by astirpe** [comment]
Temporary patch reverted for now, since issue https://github.com/OCA/web/issues/2682 prevents the Odoo PDF preview to be opened automatically.

**Comment by ThijsvOers** [comment]
@astirpe Antonio found the solution, he disabled the OCA preview module on vendor bills
